image: proboci/ubuntu-14.04-lamp:php-7.1
steps:
  - name: Test if registry_rebuild is installed.
    plugin: Script
    script:
      - drush rr
  - name: Add registry_rebuild
    plugin: Script
    script:
      - drush @none dl registry_rebuild-7.x
      - drush cc drush
  - name: Test if registry_rebuild is installed again.
    plugin: Script
    script:
      - drush rr
