steps:
  - name: Apt-get update repositories.
    plugin: Script
    script:
      - apt-get -qq update
  - name: Apt-get upgrade packages.
    plugin: Script
    script:
      - "DEBIAN_FRONTEND=noninteractive apt-get upgrade"
