steps:
  - name: Apt-get update repositories.
    plugin: Script
    script:
      - apt-get update
  - name: Apt-get upgrade packages.
    plugin: Script
    script:
      - "ENV DEBIAN_FRONTEND=noninteractive apt-get upgrade"
